local config = {}

-- AIDA64 RemoteSensor server on the Windows host.
config.host = "192.168.0.232"
config.port = 9999
config.layout_path = "/"
config.path = "/sse"
-- A single OFL-licensed Chinese TrueType face is rasterized on device at the
-- exact size requested by AIDA64. Keep the family name in sync with WebUI.
config.vector_font_family = "AIDA Noto Sans SC"
config.vector_font_module = "/sd/apps/aida_monitor/modules/aida_font.so"
config.vector_font_path = "/sd/apps/aida_monitor/font/aida_noto_sans_sc.ttf"
-- LCD stripe order. Use "bgr" if colored fringes look reversed, or "off"
-- when the panel/optics do not preserve physical subpixels.
config.font_subpixel = "rgb"
-- LEFT/RIGHT are generated by HoloCubic's gravity sensor. The cooldown absorbs
-- the START+SHORT burst so one physical tilt changes exactly one page.
config.tilt_page_cooldown_ms = 1000

config.timeout_ms = 7000
config.reconnect_ms = 2000
config.stale_ms = 5000
config.watchdog_ms = 1000
config.layout_retry_ms = 3000
config.reload_delay_ms = 500
config.max_layout_bytes = 196608
config.history_points = 96
config.cache_dir = "/sd/apps/aida_monitor/cache"
config.max_image_bytes = 262144
config.max_image_pixels = 307200
config.image_timeout_ms = 7000
config.serial_log = true

return config
